version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - app_network

  mysql:
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${MYSQL_FORWARD_PORT:-3306}:3306"
    volumes:
      - mysql:/var/lib/mysql
    command:
      - --character-set-client-handshake=OFF
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - app_network

  redis:
    image: redis:latest
    restart: always
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_FORWARD_PORT:-6379}:6379"
    volumes:
      - redis:/root/redis
    networks:
      - app_network

  liquibase:
    image: liquibase/liquibase
    environment:
      INSTALL_MYSQL: 'true'
    volumes:
      - ./database/liquibase/dbchangelog.yaml:/liquibase/dbchangelog.yaml
      - ./database/liquibase/seed:/liquibase/seed
    networks:
      - app_network
    depends_on:
      - mysql

volumes:
  mysql:
  redis:

networks:
  app_network:
    driver: bridge
